name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  ci-lint:
    uses: kurocado-studio/styleguide/.github/workflows/lint.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
