name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run Lint Workflow
        uses: kurocado-studio/styleguide/.github/workflows/lint.yml@main
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
