name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write


jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get composites
        uses: actions/checkout@v2
        with:
          repository: kurocado-studio/styleguide
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/actions

  ci-lint:
    uses: kurocado-studio/styleguide/.github/workflows/lint.yml@main
    needs: [checkout]
    secrets: inherit
