name: Release Workflow

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  ci-release:
    uses: kurocado-studio/styleguide/.github/workflows/release.yml@main
    secrets: inherit

  ci-documentation:
    uses: kurocado-studio/styleguide/.github/workflows/documentation.yml@main
    needs: [ci-release]
    secrets: inherit
