name: Release Workflow

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  manage-release:
    uses: kurocado-studio/styleguide/.github/workflows/release.yml@main
    secrets: inherit

  generate-documentation:
    uses: kurocado-studio/styleguide/.github/workflows/writerside-documentation.yml@main
    secrets: inherit
