name: Release Workflow

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

  ci-release:
    uses: kurocado-studio/styleguide/.github/workflows/release.yml@main
    needs: [checkout]
    secrets: inherit

  ci-documentation:
    uses: kurocado-studio/styleguide/.github/workflows/documentation.yml@main
    needs: [ci-release]
    secrets: inherit
